# Dockerfile for the Expo React Native app
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install -g expo-cli
RUN npm install

# Bundle app source
COPY . .

# Start the app
CMD ["npx", "expo", "run", "ios"]

